CREATE TABLE IF NOT EXISTS "todo_users" (
  "id" text PRIMARY KEY,
  "phone" varchar(20) NOT NULL UNIQUE,
  "password" text NOT NULL,
  "name" varchar(100),
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "todo_categories" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "todo_users"("id") ON DELETE CASCADE,
  "name" varchar(80) NOT NULL,
  "color" varchar(20),
  "sortOrder" integer NOT NULL DEFAULT 0,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "todo_categories_userId_name_key" UNIQUE ("userId", "name")
);

CREATE TABLE IF NOT EXISTS "todo_tags" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "todo_users"("id") ON DELETE CASCADE,
  "name" varchar(50) NOT NULL,
  "color" varchar(20),
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "todo_tags_userId_name_key" UNIQUE ("userId", "name")
);

CREATE TABLE IF NOT EXISTS "todo_todos" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "todo_users"("id") ON DELETE CASCADE,
  "categoryId" text REFERENCES "todo_categories"("id") ON DELETE SET NULL,
  "title" varchar(200) NOT NULL,
  "content" text,
  "status" varchar(20) NOT NULL DEFAULT 'todo',
  "priority" integer NOT NULL DEFAULT 2,
  "isPinned" boolean NOT NULL DEFAULT false,
  "dueDate" timestamptz,
  "completedAt" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now(),
  "deletedAt" timestamptz
);

ALTER TABLE "todo_todos" ADD COLUMN IF NOT EXISTS "isPinned" boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "todo_todo_tags" (
  "id" text PRIMARY KEY,
  "todoId" bigint NOT NULL REFERENCES "todo_todos"("id") ON DELETE CASCADE,
  "tagId" text NOT NULL REFERENCES "todo_tags"("id") ON DELETE CASCADE,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "todo_todo_tags_todoId_tagId_key" UNIQUE ("todoId", "tagId")
);

CREATE TABLE IF NOT EXISTS "todo_history" (
  "id" text PRIMARY KEY,
  "todoId" bigint NOT NULL REFERENCES "todo_todos"("id") ON DELETE CASCADE,
  "userId" text NOT NULL REFERENCES "todo_users"("id") ON DELETE CASCADE,
  "action" varchar(50) NOT NULL,
  "beforeValue" jsonb,
  "afterValue" jsonb,
  "createdAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "todo_reminders" (
  "id" text PRIMARY KEY,
  "todoId" bigint NOT NULL REFERENCES "todo_todos"("id") ON DELETE CASCADE,
  "userId" text NOT NULL REFERENCES "todo_users"("id") ON DELETE CASCADE,
  "remindAt" timestamptz NOT NULL,
  "repeatIntervalMinutes" integer NOT NULL DEFAULT 5,
  "lastNotifiedAt" timestamptz,
  "dismissedAt" timestamptz,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "todo_notifications" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "todo_users"("id") ON DELETE CASCADE,
  "todoId" bigint REFERENCES "todo_todos"("id") ON DELETE SET NULL,
  "title" varchar(200) NOT NULL,
  "body" varchar(500) NOT NULL,
  "kind" varchar(30) NOT NULL DEFAULT 'reminder',
  "isRead" boolean NOT NULL DEFAULT false,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "readAt" timestamptz
);

CREATE TABLE IF NOT EXISTS "todo_push_subscriptions" (
  "id" text PRIMARY KEY,
  "userId" text NOT NULL REFERENCES "todo_users"("id") ON DELETE CASCADE,
  "endpoint" text NOT NULL UNIQUE,
  "deviceName" varchar(120),
  "p256dh" text NOT NULL,
  "auth" text NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true,
  "createdAt" timestamptz NOT NULL DEFAULT now(),
  "updatedAt" timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "todo_categories_userId_idx" ON "todo_categories" ("userId");
CREATE INDEX IF NOT EXISTS "todo_tags_userId_idx" ON "todo_tags" ("userId");
CREATE INDEX IF NOT EXISTS "todo_todos_userId_idx" ON "todo_todos" ("userId");
CREATE INDEX IF NOT EXISTS "todo_todos_categoryId_idx" ON "todo_todos" ("categoryId");
CREATE INDEX IF NOT EXISTS "todo_todos_status_idx" ON "todo_todos" ("status");
CREATE INDEX IF NOT EXISTS "todo_todos_priority_idx" ON "todo_todos" ("priority");
CREATE INDEX IF NOT EXISTS "todo_todos_isPinned_idx" ON "todo_todos" ("isPinned");
CREATE INDEX IF NOT EXISTS "todo_todos_dueDate_idx" ON "todo_todos" ("dueDate");
CREATE INDEX IF NOT EXISTS "todo_todos_createdAt_idx" ON "todo_todos" ("createdAt");
CREATE INDEX IF NOT EXISTS "todo_todos_deletedAt_idx" ON "todo_todos" ("deletedAt");
CREATE INDEX IF NOT EXISTS "todo_todo_tags_todoId_idx" ON "todo_todo_tags" ("todoId");
CREATE INDEX IF NOT EXISTS "todo_todo_tags_tagId_idx" ON "todo_todo_tags" ("tagId");
CREATE INDEX IF NOT EXISTS "todo_history_todoId_idx" ON "todo_history" ("todoId");
CREATE INDEX IF NOT EXISTS "todo_history_userId_idx" ON "todo_history" ("userId");
CREATE INDEX IF NOT EXISTS "todo_reminders_todoId_idx" ON "todo_reminders" ("todoId");
CREATE INDEX IF NOT EXISTS "todo_reminders_userId_idx" ON "todo_reminders" ("userId");
CREATE INDEX IF NOT EXISTS "todo_reminders_remindAt_idx" ON "todo_reminders" ("remindAt");
CREATE INDEX IF NOT EXISTS "todo_notifications_userId_idx" ON "todo_notifications" ("userId");
CREATE INDEX IF NOT EXISTS "todo_notifications_todoId_idx" ON "todo_notifications" ("todoId");
CREATE INDEX IF NOT EXISTS "todo_notifications_isRead_idx" ON "todo_notifications" ("isRead");
CREATE INDEX IF NOT EXISTS "todo_push_subscriptions_userId_idx" ON "todo_push_subscriptions" ("userId");
